### ISSUE TITLE
snp_motion_execution ros2 control goal rejected

### ISSUE THREAD

**Issue by Yolnan** [ros-industrial-consortium/scan_n_plan_workshop#102]
In ROS2 Humble the joint_trajectory_position controller does not support trajectories with effort fields and will reject the follow joint trajectory action goal. This can be recreated on the [snp_blending implementation](https://github.com/ros-industrial-consortium/snp_blending/tree/master) by running `ros2 launch snp_blending start.launch.xml bypass_execution:=false`.

A possible fix is to remove the effort data in the JointTrajectory msg that is returned by the planning server.

**Comment by marip8** [comment]
Closing; addressed [here](https://github.com/ros-industrial-consortium/scan_n_plan_workshop/blob/7f9d9e379628a582f32a8aba5255eb1c21b43171/snp_application/src/bt/snp_bt_ros_nodes.cpp#L412) in #111
