### ISSUE TITLE
Getting Error while doing vcs import < src/scan_n_plan_workshop/dependencies_tesseract.repos

### ISSUE THREAD

**Issue by arulfrances** [ros-industrial-consortium/scan_n_plan_workshop#116]
Team,

I have cloned the repo  and while doing vcs import, I am getting the following error:

![image](https://github.com/ros-industrial-consortium/scan_n_plan_workshop/assets/7755566/4f32f48f-85c7-473d-8226-045da3c1c20c)

Please guide me in the right direction.

P.S: My internet connection is perfectly stable.

What I tried:
git fetch --unshallow
git fetch --depth=2147483647

But it didn't help! 

Thanks

**Comment by marip8** [comment]
The process should be:

```bash
cd <snp_workspace>
vcs import src < src/scan_n_plan_workshop/dependencies_tesseract.repos
```

Some of the repos like `tesseract` are fairly large, so you could also try using a shallow clone to make the process go faster (i.e., `vcs import --shallow src < src/scan_n_plan_workshop/dependencies_tesseract.repos`)

Closing; this was added to the README in #122

**Comment by arulfrances** [comment]
Thanks a lot @marip8  for your support as always!

After adding the shallow command, I was able to build the App without any issues!

Keep up the great work on supporting the community!
