### ISSUE TITLE
dependencies_tesseract.repos repos do not contain C language 

### ISSUE THREAD

**Issue by wglockner** [ros-industrial-consortium/scan_n_plan_workshop#149]
Following the instructions on the README while trying to build on Humble 22.04 leads to the error message: 
```commandline
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/vtk-9.1/VTK-targets.cmake:518 (set_target_properties):
  The link interface of target "VTK::mpi" contains:

    MPI::MPI_C

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/vtk-9.1/vtk-config.cmake:138 (include)
  /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:270 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:319 (find_VTK)
  /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:540 (find_external_library)
  CMakeLists.txt:15 (find_package)
```
I have not yet been able to find the correct combinations with the latest compatible versions of each repo. Could the dependencies_tesseract.repos and/or dependencies.repos be updated with the latest compatible versions?

**Comment by marip8** [comment]
The addition of the `C` flag happened after `tesseract` version 0.22.x, so it can be a bit tricky to get that version of `tesseract` to build on 22.04. Locally, I cherry-picked the commits from @rjoomen that add this fix on top of the versions of the `tesseract` repositories that are specified in the `dependencies.repos` file. I just added new patch branches and tags to fix this in the `tesseract` repositories, and opened #151 to update this repository accordingly. Try using those branches instead; that should solve this issue
