### ISSUE TITLE
Is there plans to update this to the latest version of Tesseract?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial-consortium/scan_n_plan_workshop#19]

**Comment by rjoomen** [comment]
Check @marrts's work [here](https://github.com/marrts/scan_n_plan_workshop/tree/update/tesseract_0.16).

**Comment by marrts** [comment]
It is running on the latest version of Tesseract on that branch, but I am holding off merging anything until https://github.com/tesseract-robotics/tesseract_planning/issues/314 is resolved.

**Comment by rjoomen** [comment]
The mentioned issue has been resolved, it would be good to centralize development again.

**Comment by rjoomen** [comment]
This can be closed
