### ISSUE TITLE
update setup script and build instructions

### ISSUE THREAD

**Issue by gautz** [ros-industrial-consortium/scan_n_plan_workshop#2]
Hello, could you please update the workshop_setup.bash (e.g. by merging #1) and update the main README with build instructions according to the experience gathered yesterday? https://docs.google.com/document/d/1U6e_0QIezguH_laEUVTDFtoztB5VAA_RYH9CIm52qIA/edit
I'd like to setup the workshop on my local machine, are there some steps from aws_setup.bash that I should follow ?

**Comment by marip8** [comment]
Closing since the repository has changed significantly since the opening of this issue. Feel free to re-open if this issue is still relevant or if you need help getting the updated version of this repository to build
