### ISSUE TITLE
Update Repository to be simply scan_plan_workshop

### ISSUE THREAD

**Issue by robinsonmm** [ros-industrial-consortium/scan_n_plan_workshop#3]
With the official work spec'd to leverage this for a demo, perhaps we version this to a more general name.

**Comment by gavanderhoorn** [comment]
What name would you want to rename it to @robinsonmm ?

**Comment by gavanderhoorn** [comment]
Not sure you get notified from edits: @marip8.

**Comment by marip8** [comment]
We were thinking to rename to `scan_n_plan_workshop`

**Comment by gavanderhoorn** [comment]
You should be able to do that now.

**Comment by marip8** [comment]
Done. Any objections to moving to the `ros-industrial` organization as well? It would be nice to have better access to CI, etc.

**Comment by marip8** [comment]
Closing as repo has been renamed
