### ISSUE TITLE
Expose StopReconstruction service arguments as parameters

### ISSUE THREAD

**Issue by DavidSpielman** [ros-industrial-consortium/scan_n_plan_workshop#91]
Several parameters for the `StopReconstruction` service are currently hard coded. We should expose them as parameters instead so they can be changed dynamically by the application

https://github.com/ros-industrial-consortium/scan_n_plan_workshop/blob/34fd88f5cb00f3820dd88b98a15fe91b3241ed86/snp_application/src/bt/snp_bt_ros_nodes.cpp#L159-L166

**Comment by marip8** [comment]
Closing; addressed in #92
