### ISSUE TITLE
Add BT Trajectory Utility Nodes

### ISSUE THREAD

**Issue by marip8** [ros-industrial-consortium/scan_n_plan_workshop#93]
Consider adding BT nodes for doing various operations to trajectories:
- Combining 2 trajectories
- Reversing a trajectory
  - Useful in a case where some operation fails when the robot is not at the home state (e.g., the call to start reconstruction fails). We could potentially reverse some known trajectory to return home
- Populating joint trajectories (e.g., from motion planners) with the current state of all robot controller joints that are missing from the trajectory
  - Useful for drivers like MotoROS2 when multiple motion groups are present

**Comment by marrts** [comment]
Might also be nice to just have a "Go Home" button that does a motion plan to the home state.
