### ISSUE TITLE
Add ability to select more than one region to apply tool paths

### ISSUE THREAD

**Issue by robinsonmm** [ros-industrial-consortium/scan_n_plan_workshop#94]
In larger reconstruction scenes it is often of interest to apply tools to do work in more than one location. Currently we can only select one region for tool path planning. Ideally we can select multiple regions on the mesh(es) apply tool paths and generate motions for each and have them run in some logical order, i.e. closest to farthest. 

Bonus that we can specify or change the order that the regions are treated.

**Comment by marip8** [comment]
Closing; addressed in #114
